stages:
  - pdf
  - deploy

pdf_stage:
  stage: pdf
  image: timnn/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  script:
    - tex --version
    - mkdir output
    - find ./ -name '*aula.tex' -exec pdflatex {} \;
    - find ./ -name '*.pdf' -exec mv -t ./output {} \;
  artifacts:
    paths: 
      - output  # instruct GitLab to keep the main.pdf file
  only:
    - master

pages:
  stage: deploy
  image: alpine:latest
  script:
    - find ./ -name '*.pdf'
    - find ./ -name '*.pdf' -exec mv -t ./public {} +
  artifacts:
    paths:
    - public
  only:
  - master
