stages:
  - pdf
  - pages

pdf_stage:
  stage: pdf
  image: timnn/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  script:
    - tex --version
    - cp 1-introducao-a-robotica-movel/beamerthemesimple.sty ./
    - find ./ -name '*aula.tex' -exec pdflatex {} \;
    - sleep 30
    - find ./ -name '*.pdf' -exec mv -t ./public {} \;
  artifacts:
    paths: 
      - public  # instruct GitLab to keep the main.pdf file
  only:
    - master

pages:
  stage: pages
  image: alpine:latest
  script:
    - echo 'deploy page!!!'
    - ls ./public/*.pdf
  artifacts:
    paths:
    - public
  only:
  - master
