stages:
  - pdf
  - pages

pdf_stage:
  stage: pdf
  image: timnn/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  script:
    - tex --version
    - cp references.bib ../
    - mkdir ./images
    - find ./ -name '*_image.tex' -exec mv -t ./images {} \;
    - find ./ -name '*.jpeg' -exec mv -t ./images {} \;
    - find ./ -name '*.jpg' -exec mv  -t ./images {} \;
    - find ./ -name '*.png' -exec mv  -t ./images {} \;
#    - find ./ -name '*.ipynb' -exec mv  -t ./public {} \;
    - cp 1-introducao-a-robotica-movel/beamerthemesimple.sty ./
    - ls
    - find ./ -name '*aula.tex' -exec pdflatex {} \;
    - find ./ -name '*.pdf' -exec mv -t ./public {} \;
    - ls ./public/
  artifacts:
    paths: 
      - public  # instruct GitLab to keep the main.pdf file
  only:
    - master

pages:
  stage: pages
  image: alpine:latest
  script:
    - echo 'deploy page!!!'
    - ls ./public/
  artifacts:
    paths:
    - public
  only:
  - master
