stages:
  - pdf
  - deploy

pdf_stage:
  stage: pdf
  image: timnn/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  script:
    - tex --version
    - find ./ -name '*aula.tex' -exec pdflatex -output-directory ./public {} \;
  artifacts:
    paths: 
      - public  # instruct GitLab to keep the main.pdf file
  only:
    - master

pages:
  stage: deploy
  image: alpine:latest
  script:
    - echo 'deploy page!!!'
  artifacts:
    paths:
    - public
  only:
  - master
