compile_pdf:
  stage: build
  image: timnn/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  script:
    - cd ./1-introducao-a-robotica-movel/
    - pdflatex cinematica-e-dinamica.tex  # build the pdf just as you would on your computer
    - mv pdflatex cinematica-e-dinamica.pdf ../
  artifacts:
    paths: 
      - cinematica-e-dinamica.pdf  # instruct GitLab to keep the main.pdf file
