# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  stage: pages
  image: registry.gitlab.com/pages/hugo:latest
  script:
    - cd ./docs/api
    - hugo
    - mv public ../../public
  artifacts:
    paths:
      - public
  only:
    - master