baseURL = "https://cursoseaulas.gitlab.io/robotica-movel"
author = "Jeferson Lima"
githubUrl = "https://gitlab.com/cursoseaulas/robotica-movel"
languageCode = "pt-br"
title = "Disciplina de Robótica Móvel"
theme = "simple-style"

