baseURL = "https://cursoseaulas.gitlab.io/robotica-movel"
author = "Jeferson Lima"
githubUrl = "https://gitlab.com/cursoseaulas/robotica-movel"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-learn"
